development:
  adapter: postgresql
  encoding: unicode
  database: bunintheoven_development
  pool: 5
  username: VajraCreations
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bunintheoven_test
  pool: 5
  username: VajraCreations
  password: