# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3856ef782778681d8ae002d41bb17806d7dcee2325f8c88785317937104374d5206956f50800313a49d75fe568af55e5e4c003722692c83fb5276f89f4a164f7

test:
  secret_key_base: 5c70590465053f2acf5a409fcc706802360ca1e2d8878de3955b76ca34128b5d4b5f7b6e5c3a248c1c18b92beaa1a5e5b4e8e316aac90351f863a7815972dc18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
